/**
 * Installer config generators shared between the ConfigurationEditor preview
 * and the Deploy Wizard (which sends the generated text to the backend API).
 *
 * Pass `callbackOpts` to inject curl callbacks so the backend learns when
 * the installer started and completed.
 */
import { DeploymentConfig } from '../types';

export interface CallbackOpts {
  /** e.g. "http://192.168.1.10:3001"  — no trailing slash */
  apiBase: string;
  /** Normalised MAC with hyphens: "aa-bb-cc-dd-ee-ff" */
  mac: string;
}

// ── Preseed (Ubuntu / Debian) ─────────────────────────────────────────────────

export function generatePreseed(cfg: DeploymentConfig, cb?: CallbackOpts): string {
  const postCmds = cfg.commands.filter(c => c.stage === 'post-install' && c.enabled);

  const lateCommandParts: string[] = [];
  if (cb) {
    lateCommandParts.push(`in-target curl -sf ${cb.apiBase}/api/callback/${cb.mac}/completed || true`);
  }
  postCmds.forEach(c => {
    const escaped = c.content.replace(/\n/g, '; ').replace(/'/g, "\\'");
    lateCommandParts.push(`in-target bash -c '${escaped}'`);
  });

  const lateCommandLine = lateCommandParts.length > 0
    ? `\n### Callbacks + post-install commands\nd-i preseed/late_command string \\\n${lateCommandParts.map(p => `  ${p} && \\`).join('\n')}\n  echo "Post-install completed"`
    : '';

  const earlyCommand = cb
    ? `\nd-i preseed/early_command string curl -sf ${cb.apiBase}/api/callback/${cb.mac}/started || true\n`
    : '';

  return `# Ubuntu/Debian Preseed Configuration
# Generated by PXE Deployer — ${cfg.name}
# ==========================================================

### Localization
d-i debian-installer/locale string ${cfg.locale}
d-i keyboard-configuration/xkb-keymap select ${cfg.keyboard}
${earlyCommand}
### Network configuration
${cfg.network.mode === 'dhcp'
  ? 'd-i netcfg/choose_interface select auto\nd-i netcfg/get_hostname string ' + cfg.network.hostnameTemplate
  : `d-i netcfg/choose_interface select auto
d-i netcfg/disable_autoconfig boolean true
d-i netcfg/get_ipaddress string ${cfg.network.ipAddress}
d-i netcfg/get_netmask string ${cfg.network.subnet}
d-i netcfg/get_gateway string ${cfg.network.gateway}
d-i netcfg/get_nameservers string ${cfg.network.dnsServers.join(' ')}
d-i netcfg/get_hostname string ${cfg.network.hostnameTemplate}
d-i netcfg/get_domain string ${cfg.network.domain}`}

### Mirror settings
d-i mirror/country string manual
d-i mirror/http/hostname string archive.ubuntu.com
d-i mirror/http/directory string /ubuntu
d-i mirror/http/proxy string

### Account setup
d-i passwd/root-login boolean false
d-i passwd/user-fullname string Deploy User
d-i passwd/username string ${cfg.adminUser || 'deploy'}
d-i passwd/user-password-crypted password [hashed-password]

### Clock and timezone
d-i clock-setup/utc boolean true
d-i time/zone string ${cfg.timezone}
d-i clock-setup/ntp boolean true

### Partitioning
${cfg.partitions.scheme === 'auto' ? `d-i partman-auto/method string regular
d-i partman-auto/choose_recipe select atomic`
  : cfg.partitions.scheme === 'lvm' ? `d-i partman-auto/method string lvm
d-i partman-auto-lvm/new_vg_name string vg0
d-i partman-lvm/device_remove_lvm boolean true
d-i partman-lvm/confirm boolean true
d-i partman-auto-lvm/guided_size string max`
  : `d-i partman-auto/method string regular
# Custom layout below`}
d-i partman-partitioning/confirm_write_new_label boolean true
d-i partman/choose_partition select finish
d-i partman/confirm boolean true

### Package selection
tasksel tasksel/first multiselect server
d-i pkgsel/include string ${cfg.packages.join(' ')}
d-i pkgsel/upgrade select full-upgrade

### Grub
d-i grub-installer/only_debian boolean true
d-i grub-installer/bootdev string default

### Finish installation
d-i finish-install/reboot_in_progress note
${lateCommandLine}
`;
}

// ── Kickstart (Rocky Linux / RHEL) ───────────────────────────────────────────

export function generateKickstart(cfg: DeploymentConfig, cb?: CallbackOpts): string {
  const preCmds  = cfg.commands.filter(c => c.stage === 'pre-install'  && c.enabled);
  const postCmds = cfg.commands.filter(c => c.stage === 'post-install' && c.enabled);

  const preSection = `%pre
${cb ? `curl -sf ${cb.apiBase}/api/callback/${cb.mac}/started || true\n` : ''}${preCmds.map(c => c.content).join('\n') || '# No pre-install commands'}
%end`;

  const postSection = `%post
${postCmds.map(c => c.content).join('\n') || '# No post-install commands'}
${cb ? `\ncurl -sf ${cb.apiBase}/api/callback/${cb.mac}/completed || true` : ''}
%end`;

  return `# Rocky Linux / RHEL Kickstart Configuration
# Generated by PXE Deployer — ${cfg.name}
# ==========================================================

#version=RHEL9
install

### Language and keyboard
lang ${cfg.locale}
keyboard --xlayouts='${cfg.keyboard}'

### Timezone
timezone ${cfg.timezone} --utc

### Network
${cfg.network.mode === 'dhcp'
  ? `network --bootproto=dhcp --device=link --activate --hostname=${cfg.network.hostnameTemplate}`
  : `network --bootproto=static --device=link --ip=${cfg.network.ipAddress} --netmask=${cfg.network.subnet} --gateway=${cfg.network.gateway} --nameserver=${cfg.network.dnsServers.join(',')} --hostname=${cfg.network.hostnameTemplate}`}

### Root and user
rootpw --lock
user --name=${cfg.adminUser || 'deploy'} --groups=wheel --gecos="Deploy User" --password=[hashed]

### Firewall
firewall --enabled --service=ssh

### SELinux
selinux --enforcing

### Bootloader
bootloader --location=mbr --boot-drive=${cfg.partitions.bootDisk}
zerombr
clearpart --all --initlabel

### Partitioning
${cfg.partitions.scheme === 'lvm'
  ? `part /boot/efi --fstype="efi" --size=${cfg.partitions.efiSize.replace('M','')} --fsoptions="umask=0077,shortname=winnt"
part /boot --fstype="xfs" --size=${cfg.partitions.bootSize.replace('G','000')}
part pv.01 --fstype="lvmpv" --size=1 --grow
volgroup vg0 pv.01
logvol swap --fstype="swap" --name=swap --vgname=vg0 --size=${parseInt(cfg.partitions.swapSize)*1024 || 4096}
logvol / --fstype="xfs" --name=root --vgname=vg0 --size=1 --grow`
  : `part /boot/efi --fstype="efi" --size=600
part /boot --fstype="xfs" --size=1024
part / --fstype="xfs" --size=1 --grow`}

### Package groups and packages
%packages
${cfg.packageGroups.join('\n')}
${cfg.packages.join('\n')}
%end

${preSection}

${postSection}
`;
}

// ── AutoUnattend (Windows Server) ────────────────────────────────────────────

export function generateAutounattend(cfg: DeploymentConfig): string {
  return `<?xml version="1.0" encoding="utf-8"?>
<!-- Windows Server 2025 AutoUnattend — ${cfg.name} -->
<!-- Generated by PXE Deployer -->
<unattend xmlns="urn:schemas-microsoft-com:unattend">
  <settings pass="windowsPE">
    <component name="Microsoft-Windows-International-Core-WinPE"
               processorArchitecture="amd64"
               publicKeyToken="31bf3856ad364e35"
               language="neutral" versionScope="nonSxS"
               xmlns:wcm="http://schemas.microsoft.com/WMIConfig/2002/State">
      <InputLocale>${cfg.keyboard}</InputLocale>
      <SystemLocale>${cfg.locale}</SystemLocale>
      <UILanguage>${cfg.locale.split('.')[0].replace('_', '-')}</UILanguage>
      <UserLocale>${cfg.locale.split('.')[0].replace('_', '-')}</UserLocale>
    </component>
    <component name="Microsoft-Windows-Setup" processorArchitecture="amd64"
               publicKeyToken="31bf3856ad364e35" language="neutral" versionScope="nonSxS">
      <DiskConfiguration>
        <Disk wcm:action="add">
          <CreatePartitions>
            <CreatePartition wcm:action="add">
              <Order>1</Order><Type>EFI</Type><Size>${cfg.partitions.efiSize.replace('M','')}</Size>
            </CreatePartition>
            <CreatePartition wcm:action="add">
              <Order>2</Order><Type>MSR</Type><Size>128</Size>
            </CreatePartition>
            <CreatePartition wcm:action="add">
              <Order>3</Order><Type>Primary</Type><Extend>true</Extend>
            </CreatePartition>
          </CreatePartitions>
          <DiskID>0</DiskID>
          <WillWipeDisk>true</WillWipeDisk>
        </Disk>
      </DiskConfiguration>
      <ImageInstall>
        <OSImage>
          <InstallTo><DiskID>0</DiskID><PartitionID>3</PartitionID></InstallTo>
        </OSImage>
      </ImageInstall>
    </component>
  </settings>
  <settings pass="specialize">
    <component name="Microsoft-Windows-Shell-Setup" processorArchitecture="amd64"
               publicKeyToken="31bf3856ad364e35" language="neutral" versionScope="nonSxS">
      <ComputerName>${cfg.network.hostnameTemplate}</ComputerName>
      <TimeZone>${cfg.timezone}</TimeZone>
    </component>
    <component name="Microsoft-Windows-TCPIP" processorArchitecture="amd64"
               publicKeyToken="31bf3856ad364e35" language="neutral" versionScope="nonSxS">
      ${cfg.network.mode === 'dhcp'
        ? '<Interfaces><Interface wcm:action="add"><Ipv4Settings><DhcpEnabled>true</DhcpEnabled></Ipv4Settings><Identifier>Local Area Connection</Identifier></Interface></Interfaces>'
        : `<Interfaces><Interface wcm:action="add"><Ipv4Settings><DhcpEnabled>false</DhcpEnabled></Ipv4Settings><UnicastIpAddresses><IpAddress wcm:action="add" wcm:keyValue="1">${cfg.network.ipAddress}/${cfg.network.subnet}</IpAddress></UnicastIpAddresses><Routes><Route wcm:action="add"><Identifier>0</Identifier><Prefix>0.0.0.0/0</Prefix><NextHopAddress>${cfg.network.gateway}</NextHopAddress></Route></Routes><Identifier>Local Area Connection</Identifier></Interface></Interfaces>`}
    </component>
  </settings>
  <settings pass="oobeSystem">
    <component name="Microsoft-Windows-Shell-Setup" processorArchitecture="amd64"
               publicKeyToken="31bf3856ad364e35" language="neutral" versionScope="nonSxS">
      <OOBE>
        <HideEULAPage>true</HideEULAPage>
        <HideLocalAccountScreen>true</HideLocalAccountScreen>
        <HideOEMRegistrationScreen>true</HideOEMRegistrationScreen>
        <HideOnlineAccountScreens>true</HideOnlineAccountScreens>
        <HideWirelessSetupInOOBE>true</HideWirelessSetupInOOBE>
        <SkipMachineOOBE>true</SkipMachineOOBE>
        <SkipUserOOBE>true</SkipUserOOBE>
      </OOBE>
      <FirstLogonCommands>
${cfg.commands.filter(c => c.stage === 'first-boot' && c.enabled).map((c, i) => `        <SynchronousCommand wcm:action="add">
          <Order>${i + 1}</Order>
          <CommandLine>powershell.exe -NonInteractive -EncodedCommand [base64-encoded]</CommandLine>
          <Description>${c.name}</Description>
        </SynchronousCommand>`).join('\n')}
      </FirstLogonCommands>
    </component>
  </settings>
</unattend>`;
}

// ── Dispatcher ────────────────────────────────────────────────────────────────

export function generateConfig(
  cfg: DeploymentConfig,
  osFamily: 'debian' | 'rhel' | 'windows',
  cb?: CallbackOpts,
): string {
  if (osFamily === 'windows') return generateAutounattend(cfg);
  if (osFamily === 'rhel')    return generateKickstart(cfg, cb);
  return generatePreseed(cfg, cb);
}
