#!/usr/bin/env bash
# =============================================================================
# setup-pxe.sh — Prepare the /srv/pxe directory structure on the staging server
#
# Run ONCE on the Linux host before starting Docker Compose.
# Requires: internet access, curl, root.
#
# Usage:
#   chmod +x setup-pxe.sh
#   sudo ./setup-pxe.sh
#   sudo API_HOST=192.168.1.10 ./setup-pxe.sh   # set staging server IP
# =============================================================================

set -euo pipefail

RED='\033[0;31m'; GREEN='\033[0;32m'; YELLOW='\033[1;33m'
CYAN='\033[0;36m'; BOLD='\033[1m'; NC='\033[0m'

step() { echo -e "\n${CYAN}${BOLD}▶ $*${NC}"; }
ok()   { echo -e "  ${GREEN}✔ $*${NC}"; }
warn() { echo -e "  ${YELLOW}⚠ $*${NC}"; }
die()  { echo -e "\n${RED}${BOLD}✘ FATAL: $*${NC}\n"; exit 1; }

[[ ${EUID} -eq 0 ]] || die "Please run as root: sudo ./setup-pxe.sh"

PXE_ROOT="${PXE_ROOT:-/srv/pxe}"
API_HOST="${API_HOST:-$(hostname -I | awk '{print $1}')}"

echo ""
echo -e "${BOLD}══════════════════════════════════════════════${NC}"
echo -e "${BOLD}  PXE Deployer — Staging Server Setup${NC}"
echo -e "${BOLD}══════════════════════════════════════════════${NC}"
echo -e "  PXE_ROOT : ${PXE_ROOT}"
echo -e "  API_HOST : ${API_HOST}"
echo ""

# ── 1. Directory structure ────────────────────────────────────────────────────
step "1/5  Creating directory structure"

mkdir -p "${PXE_ROOT}/tftp/grub"
mkdir -p "${PXE_ROOT}/http/configs"
mkdir -p "${PXE_ROOT}/http/images"

# Permissions — www-data for nginx, readable by dnsmasq/tftpd
chmod 755 "${PXE_ROOT}/tftp"
chmod 755 "${PXE_ROOT}/http"
chmod 777 "${PXE_ROOT}/http/configs"   # API writes here
chmod 777 "${PXE_ROOT}/tftp/grub"      # API writes here

ok "Directory structure created at ${PXE_ROOT}"

# ── 2. Download GRUB2 EFI binary ─────────────────────────────────────────────
step "2/5  Downloading GRUB2 EFI binary (grubnetx64.efi)"

GRUB_EFI="${PXE_ROOT}/tftp/grubnetx64.efi"

if [[ -f "${GRUB_EFI}" ]]; then
  ok "grubnetx64.efi already present — skipping download"
else
  # Ubuntu's signed GRUB EFI binary works for non-Secure Boot UEFI PXE.
  # For Secure Boot use shimx64.efi + grubx64.efi instead.
  apt-get install -y -qq grub-efi-amd64-signed 2>/dev/null || true

  GRUB_SRC=$(find /usr/lib/grub -name "grubnetx64.efi*" 2>/dev/null | head -1 || true)
  if [[ -n "${GRUB_SRC}" ]]; then
    cp "${GRUB_SRC}" "${GRUB_EFI}"
    ok "Installed from grub-efi-amd64-signed package"
  else
    # Fallback: download directly from Ubuntu CDN
    UBUNTU_POOL="http://archive.ubuntu.com/ubuntu/dists/jammy/main/uefi/grub2-amd64/current"
    curl -fsSL "${UBUNTU_POOL}/grubnetx64.efi.signed" -o "${GRUB_EFI}"
    ok "Downloaded from Ubuntu archive"
  fi
fi

# ── 3. Write default GRUB menu ────────────────────────────────────────────────
step "3/5  Writing default GRUB menu"

cat > "${PXE_ROOT}/tftp/grub/grub.cfg" <<'GRUBEOF'
# PXE Deployer — Default GRUB Menu
# If no per-MAC config is found, boot from local disk.

set timeout=5
set default=0

insmod all_video

menuentry "Boot from local disk" {
  exit
}

menuentry "PXE Shell (debug)" {
  set pager=1
  ls
}
GRUBEOF

ok "Default GRUB menu written"

# ── 4. Write .env for Docker Compose ─────────────────────────────────────────
step "4/5  Writing .env file"

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ENV_FILE="${SCRIPT_DIR}/../.env"

cat > "${ENV_FILE}" <<EOF
# PXE Deployer environment — auto-generated by setup-pxe.sh
# Edit as needed before running docker compose up

PXE_ROOT=${PXE_ROOT}
API_HOST=${API_HOST}
PXE_UI_PORT=8080
EOF

ok ".env written to $(realpath "${ENV_FILE}")"

# ── 5. Summary ────────────────────────────────────────────────────────────────
step "5/5  Setup complete"

echo ""
echo -e "${GREEN}${BOLD}  ════════════════════════════════════════════════${NC}"
echo -e "${GREEN}${BOLD}  ✔  PXE directory ready!${NC}"
echo -e "${GREEN}${BOLD}  ════════════════════════════════════════════════${NC}"
echo ""
echo -e "  Next steps:"
echo -e "  1. Download netboot images for each OS you need:"
echo -e "     ${YELLOW}sudo ./download-netboot-images.sh${NC}"
echo ""
echo -e "  2. Start all services:"
echo -e "     ${YELLOW}docker compose up -d${NC}"
echo ""
echo -e "  3. Open the management UI:"
echo -e "     ${CYAN}http://${API_HOST}:8080${NC}"
echo ""
echo -e "  4. In Settings → Backend API, enter:"
echo -e "     ${CYAN}http://${API_HOST}:3001${NC}"
echo ""
echo -e "  DHCP/TFTP config: edit ${YELLOW}deploy/dnsmasq.conf${NC}"
echo -e "  Then restart:  ${YELLOW}docker compose restart pxe-dnsmasq${NC}"
echo ""
