import React, { useState } from 'react';
import toast from 'react-hot-toast';
import {
  Plus, Trash2, Edit3, Star, ArrowUp, ArrowDown,
  BookOpen, Settings, Eye,
} from 'lucide-react';
import { useAppSelector, useAppDispatch } from '../store/hooks';
import { addEntry, updateEntry, deleteEntry, reorderEntries } from '../store/slices/bootMenuSlice';
import Card, { CardHeader, CardBody } from '../components/shared/Card';
import Button from '../components/shared/Button';
import Modal, { ConfirmDialog } from '../components/shared/Modal';
import OSIcon from '../components/shared/OSIcon';
import { Input, Select } from '../components/shared/FormField';
import { BootMenuEntry } from '../types';
import { generateId } from '../lib/utils';

function generatePxelinuxConf(entries: BootMenuEntry[], timeout: number, osProfiles: any[]): string {
  const lines = [
    '# PXE Boot Menu — Generated by PXE Deployer',
    '# =================================================',
    'UI menu.c32',
    '',
    `TIMEOUT ${timeout * 10}`,
    'PROMPT 0',
    '',
    'MENU TITLE  PXE Boot Menu — Infrastructure Provisioning',
    'MENU BACKGROUND pxelinux.cfg/boot_bg.png',
    'MENU COLOR title 1;36;40 #aa00ff00 #00000000',
    'MENU COLOR border 30;44 #40ffffff #a0000000',
    'MENU COLOR sel 7;37;40 #e0ffffff #20ffffff',
    '',
  ];

  const defaultEntry = entries.find(e => e.isDefault);
  if (defaultEntry) lines.push(`DEFAULT ${defaultEntry.id}`);
  lines.push('');

  entries.forEach(entry => {
    const os = osProfiles.find((o: any) => o.id === entry.osProfileId);
    lines.push(`LABEL ${entry.id}`);
    lines.push(`  MENU LABEL ${entry.label}`);
    if (entry.isDefault) lines.push('  MENU DEFAULT');
    if (os?.family === 'windows') {
      lines.push(`  KERNEL pxeboot.0`);
    } else {
      lines.push(`  KERNEL vmlinuz-${os?.version || 'latest'}`);
      lines.push(`  APPEND initrd=initrd.img ${entry.kernelArgs} auto=true priority=critical`);
    }
    lines.push('');
  });

  lines.push('LABEL local');
  lines.push('  MENU LABEL Boot from Local Drive');
  lines.push('  LOCALBOOT 0');

  return lines.join('\n');
}

function generateGrubConf(entries: BootMenuEntry[], timeout: number, osProfiles: any[]): string {
  const lines = [
    '# GRUB2 PXE Network Boot Configuration',
    '# Generated by PXE Deployer',
    '',
    `set timeout=${timeout}`,
    'set default=0',
    '',
    'insmod all_video',
    'insmod gfxterm',
    'insmod png',
    '',
    'if loadfont unicode ; then',
    '  set gfxmode=auto',
    '  terminal_output gfxterm',
    'fi',
    '',
  ];

  entries.forEach(entry => {
    const os = osProfiles.find((o: any) => o.id === entry.osProfileId);
    lines.push(`menuentry "${entry.label}" --id="${entry.id}" {`);
    if (os?.family === 'windows') {
      lines.push(`  chainloader (pxe)/bootmgr.exe`);
    } else {
      lines.push(`  linux (pxe)/vmlinuz-${os?.version || 'latest'} ${entry.kernelArgs} auto=true priority=critical`);
      lines.push(`  initrd (pxe)/initrd.img`);
    }
    lines.push('}');
    lines.push('');
  });

  lines.push('menuentry "Boot from Local Drive" {');
  lines.push('  exit');
  lines.push('}');

  return lines.join('\n');
}

export default function BootMenu() {
  const dispatch = useAppDispatch();
  const entries = useAppSelector(s => s.bootMenu.entries);
  const osProfiles = useAppSelector(s => s.osProfiles.profiles);
  const configurations = useAppSelector(s => s.configurations.configs);
  const settings = useAppSelector(s => s.settings);

  const [showCreate, setShowCreate] = useState(false);
  const [editEntry, setEditEntry] = useState<BootMenuEntry | null>(null);
  const [deleteId, setDeleteId] = useState<string | null>(null);
  const [previewFormat, setPreviewFormat] = useState<'pxelinux' | 'grub'>('pxelinux');
  const [showPreview, setShowPreview] = useState(false);

  const [form, setForm] = useState<Partial<BootMenuEntry>>({
    label: '',
    osProfileId: '',
    configurationId: '',
    kernelArgs: '',
    isDefault: false,
  });

  const openCreate = () => {
    setForm({ label: '', osProfileId: '', configurationId: '', kernelArgs: '', isDefault: false });
    setShowCreate(true);
  };

  const openEdit = (entry: BootMenuEntry) => {
    setEditEntry(entry);
    setForm({ ...entry });
  };

  const handleSave = () => {
    if (!form.label || !form.osProfileId) return;
    if (editEntry) {
      dispatch(updateEntry({ ...editEntry, ...form } as BootMenuEntry));
      setEditEntry(null);
      toast.success(`Boot entry "${form.label}" updated`);
    } else {
      dispatch(addEntry({
        id: generateId('boot'),
        label: form.label || '',
        osProfileId: form.osProfileId || '',
        configurationId: form.configurationId || '',
        kernelArgs: form.kernelArgs || '',
        isDefault: form.isDefault || false,
        order: entries.length + 1,
      }));
      setShowCreate(false);
      toast.success(`Boot entry "${form.label}" added`);
    }
  };

  const moveEntry = (idx: number, dir: 'up' | 'down') => {
    const newEntries = [...entries];
    const swapIdx = dir === 'up' ? idx - 1 : idx + 1;
    if (swapIdx < 0 || swapIdx >= newEntries.length) return;
    [newEntries[idx], newEntries[swapIdx]] = [newEntries[swapIdx], newEntries[idx]];
    dispatch(reorderEntries(newEntries.map((e, i) => ({ ...e, order: i + 1 }))));
  };

  const previewContent = previewFormat === 'pxelinux'
    ? generatePxelinuxConf(entries, settings.pxeMenuTimeout, osProfiles)
    : generateGrubConf(entries, settings.pxeMenuTimeout, osProfiles);

  const FormContent = () => (
    <div className="space-y-4">
      <Input
        label="Menu Label *"
        value={form.label || ''}
        onChange={e => setForm(f => ({ ...f, label: e.target.value }))}
        placeholder="Ubuntu 22.04 LTS — Web Server"
      />
      <div className="grid grid-cols-2 gap-4">
        <Select
          label="OS Profile *"
          value={form.osProfileId || ''}
          onChange={e => setForm(f => ({ ...f, osProfileId: e.target.value, configurationId: '' }))}
        >
          <option value="">— Select OS —</option>
          {osProfiles.map(os => (
            <option key={os.id} value={os.id}>{os.name} {os.version}</option>
          ))}
        </Select>
        <Select
          label="Configuration"
          value={form.configurationId || ''}
          onChange={e => setForm(f => ({ ...f, configurationId: e.target.value }))}
          disabled={!form.osProfileId}
        >
          <option value="">— Select Config —</option>
          {configurations.filter(c => c.osProfileId === form.osProfileId).map(cfg => (
            <option key={cfg.id} value={cfg.id}>{cfg.name}</option>
          ))}
        </Select>
      </div>
      <Input
        label="Extra Kernel Arguments"
        value={form.kernelArgs || ''}
        onChange={e => setForm(f => ({ ...f, kernelArgs: e.target.value }))}
        placeholder="quiet splash net.ifnames=0"
        mono
      />
      <label className="flex items-center gap-3 cursor-pointer">
        <div className="relative inline-flex items-center">
          <input
            type="checkbox"
            checked={form.isDefault || false}
            onChange={e => setForm(f => ({ ...f, isDefault: e.target.checked }))}
            className="sr-only peer"
          />
          <div className="w-10 h-5 bg-slate-700 rounded-full peer peer-checked:bg-blue-600 after:content-[''] after:absolute after:top-0.5 after:start-[2px] after:bg-white after:rounded-full after:h-4 after:w-4 after:transition-all peer-checked:after:translate-x-5" />
        </div>
        <span className="text-sm text-slate-300">Default boot entry</span>
      </label>
    </div>
  );

  return (
    <div className="space-y-6">
      {/* Header */}
      <div className="flex items-center justify-between gap-4">
        <div />
        <div className="flex gap-2">
          <Button variant="secondary" icon={<Eye size={16} />} onClick={() => setShowPreview(true)}>
            Preview Config
          </Button>
          <Button icon={<Plus size={16} />} onClick={openCreate}>
            Add Entry
          </Button>
        </div>
      </div>

      {/* Boot menu settings */}
      <Card>
        <CardHeader>
          <h3 className="text-sm font-semibold text-slate-200 flex items-center gap-2">
            <Settings size={15} className="text-slate-400" />
            Boot Menu Settings
          </h3>
        </CardHeader>
        <CardBody>
          <div className="grid grid-cols-1 sm:grid-cols-3 gap-4">
            <div>
              <label className="block text-xs font-medium text-slate-400 mb-1.5">Default Timeout (seconds)</label>
              <input type="number" value={settings.pxeMenuTimeout} readOnly
                className="w-full rounded-xl px-3 py-2 text-sm text-slate-200 border border-white/[0.07] bg-white/[0.03] focus:outline-none cursor-not-allowed opacity-70" />
              <p className="text-xs text-slate-600 mt-1">Configure in Settings page</p>
            </div>
            <div>
              <label className="block text-xs font-medium text-slate-400 mb-1.5">TFTP Root</label>
              <code className="block text-xs text-slate-300 bg-white/[0.04] border border-white/[0.07] rounded-xl px-3 py-2 font-mono">{settings.tftpRoot}</code>
            </div>
            <div>
              <label className="block text-xs font-medium text-slate-400 mb-1.5">TFTP Server</label>
              <code className="block text-xs text-slate-300 bg-white/[0.04] border border-white/[0.07] rounded-xl px-3 py-2 font-mono">{settings.tftpServer}</code>
            </div>
          </div>
        </CardBody>
      </Card>

      {/* Entries list */}
      <Card>
        <CardHeader>
          <h3 className="text-sm font-semibold text-slate-200 flex items-center gap-2">
            <BookOpen size={15} className="text-slate-400" />
            Boot Entries ({entries.length})
          </h3>
        </CardHeader>
        <CardBody className="space-y-2 p-4">
          {entries.length === 0 ? (
            <div className="flex flex-col items-center justify-center h-32 gap-3 text-slate-500">
              <div className="w-12 h-12 rounded-2xl bg-white/[0.03] border border-white/[0.06] flex items-center justify-center">
                <BookOpen size={22} className="text-slate-600" />
              </div>
              <p className="text-sm">No boot entries configured</p>
              <Button size="sm" icon={<Plus size={14} />} onClick={openCreate}>Add first entry</Button>
            </div>
          ) : (
            entries.map((entry, idx) => {
              const os = osProfiles.find(o => o.id === entry.osProfileId);
              const cfg = configurations.find(c => c.id === entry.configurationId);
              return (
                <div key={entry.id}
                  className="flex items-center gap-3 p-3 rounded-xl bg-white/[0.02] border border-white/[0.05] hover:border-white/[0.09] transition-all group">
                  <div className="w-7 h-7 rounded-lg bg-white/[0.05] flex items-center justify-center text-xs font-bold text-slate-400 flex-shrink-0">
                    {idx + 1}
                  </div>
                  {os && <OSIcon icon={os.icon} color={os.color} size="sm" />}
                  <div className="flex-1 min-w-0">
                    <div className="flex items-center gap-2">
                      <span className="text-sm font-medium text-slate-200 truncate">{entry.label}</span>
                      {entry.isDefault && (
                        <span className="inline-flex items-center gap-1 text-xs text-yellow-400 bg-yellow-900/30 border border-yellow-800/40 px-1.5 py-0.5 rounded-md flex-shrink-0">
                          <Star size={10} /> Default
                        </span>
                      )}
                    </div>
                    <div className="flex gap-3 mt-0.5 text-xs text-slate-500">
                      {cfg && <span>{cfg.name}</span>}
                      {entry.kernelArgs && (
                        <code className="text-slate-600 font-mono">{entry.kernelArgs}</code>
                      )}
                    </div>
                  </div>
                  <div className="flex items-center gap-1 opacity-0 group-hover:opacity-100 transition-opacity">
                    <button onClick={() => moveEntry(idx, 'up')} disabled={idx === 0}
                      className="p-1 text-slate-600 hover:text-slate-300 disabled:opacity-30 transition-colors">
                      <ArrowUp size={14} />
                    </button>
                    <button onClick={() => moveEntry(idx, 'down')} disabled={idx === entries.length - 1}
                      className="p-1 text-slate-600 hover:text-slate-300 disabled:opacity-30 transition-colors">
                      <ArrowDown size={14} />
                    </button>
                    <button onClick={() => openEdit(entry)}
                      className="p-1 text-slate-600 hover:text-slate-200 transition-colors">
                      <Edit3 size={14} />
                    </button>
                    <button onClick={() => setDeleteId(entry.id)}
                      className="p-1 text-slate-600 hover:text-red-400 transition-colors">
                      <Trash2 size={14} />
                    </button>
                  </div>
                </div>
              );
            })
          )}
        </CardBody>
      </Card>

      {/* Preview Modal */}
      <Modal open={showPreview} onClose={() => setShowPreview(false)}
        title="Boot Menu Configuration Preview" size="xl">
        <div className="space-y-4">
          <div className="flex gap-2">
            {(['pxelinux', 'grub'] as const).map(fmt => (
              <button key={fmt} onClick={() => setPreviewFormat(fmt)}
                className={`px-4 py-2 text-sm rounded-xl font-medium transition-all ${
                  previewFormat === fmt
                    ? 'bg-blue-600 text-white shadow-lg shadow-blue-600/30'
                    : 'bg-white/[0.05] text-slate-300 hover:bg-white/[0.08] border border-white/[0.07]'
                }`}>
                {fmt === 'pxelinux' ? 'PXELinux (BIOS)' : 'GRUB2 (UEFI)'}
              </button>
            ))}
          </div>
          <pre className="text-xs text-slate-300 bg-black/40 p-4 rounded-xl border border-white/[0.07] overflow-auto max-h-96 leading-relaxed font-mono">
            {previewContent}
          </pre>
        </div>
      </Modal>

      {/* Create/Edit Modal */}
      <Modal open={showCreate || !!editEntry}
        onClose={() => { setShowCreate(false); setEditEntry(null); }}
        title={editEntry ? 'Edit Boot Entry' : 'Add Boot Entry'}
        footer={<div className="flex justify-end gap-3">
          <Button variant="secondary" onClick={() => { setShowCreate(false); setEditEntry(null); }}>Cancel</Button>
          <Button onClick={handleSave} disabled={!form.label || !form.osProfileId}>
            {editEntry ? 'Save Changes' : 'Add Entry'}
          </Button>
        </div>}>
        <FormContent />
      </Modal>

      {/* Delete Confirm */}
      <ConfirmDialog open={!!deleteId} onClose={() => setDeleteId(null)}
        onConfirm={() => {
          if (deleteId) {
            const entry = entries.find(e => e.id === deleteId);
            dispatch(deleteEntry(deleteId));
            toast.success(`Boot entry "${entry?.label}" removed`);
          }
        }}
        title="Delete Boot Entry" confirmLabel="Delete Entry"
        description="Remove this entry from the PXE boot menu?" />
    </div>
  );
}
